[profile.default]
src  = "src"
out  = "out"
libs = ["lib"]

# ✨ NEW — tell Forge where to look when an import starts with `openzeppelin-contracts/`
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

solc_version = "0.8.24"